controller_manager_ns: controller_manager
controller_list:
  - name: cool1000/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [ joint1, joint2, joint3, joint4, joint5, joint6, joint7 ]

  - name: cool1000/gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
     - joint8
